### ISSUE TITLE
inverse_of: falsey 

### ISSUE THREAD

**Issue by ronen** [lowjoel/schema_plus_association_inverses#1]
WBN to be able to declare an association with `inverse_of: false` or `inverse_of: nil` to indicate that no inverse is intended, and so suppress the exception.

**Comment by lowjoel** [comment]
Sounds good!

Also I really need to find ways to properly display warning messages. Bullet (the gem) has a few. Would we need some sort of notification mechanism for any of the other schema plus family of gems?

**Comment by ronen** [comment]
> Also I really need to find ways to properly display warning messages.

I think that for this sort of basic extension to AR functionality, all that's needed is to raise the exception as your code currently does.   Clients can use whatever method they want, if any, to catch and display such exceptions.

**Comment by lowjoel** [comment]
True. It also has the ability to be tested during tests.
